name: Snyk Static Check
description: A reusable composite action to run Snyk IaC, Code dependency, or SAST scans

inputs:
  snyk-org:
    description: The Snyk organization
    required: true

  snyk-endpoint:
    description: The custom Snyk API endpoint (optional if using default)
    required: false
    default: "https://app.eu.snyk.io/api"

  snyk-token:
    description: The Snyk API token
    required: true

  severity-threshold:
    description: Minimum severity threshold to report (low, medium, high, critical)
    required: false
    default: "low"

  scan-mode:
    description: Choose which type of scan to run (iac, code, or sast)
    required: true

  code-file:
    description: The dependency file to scan (e.g., requirements.txt, poetry.lock)
    required: false
    default: "requirements.txt"

  sast-path:
    description: Path to scan for SAST analysis (defaults to current directory)
    required: false
    default: "."

  sast-include:
    description: Comma-separated list of file extensions or paths to include in SAST scan
    required: false
    default: ""

  sast-exclude:
    description: Comma-separated list of file extensions or paths to exclude from SAST scan
    required: false
    default: ""

  skip-unresolved:
    description: Add the --skip-unresolved flag (true/false)
    required: false
    default: "false"

  exclude-licenses:
    description: Add the --exclude-licenses flag (true/false)
    required: false
    default: "false"

  json-output-file:
    required: false
    type: string
    description: Snyk JSON file output
    default: snyk.json

  update-pr-with-scan-results:
    required: false
    type: boolean
    description: Update PR with scan results
    default: false

  use-policy-file:
    description: Whether to use a .snyk policy file to ignore known/approved issues
    required: false
    default: "true"

  policy-file-path:
    description: Path to a custom .snyk policy file (relative to the repo root)
    required: false
    default: "."

  install-requirements:
    description: Whether to install Python requirements before scanning
    required: false
    type: boolean
    default: false

  python-package-manager:
    description: Python package manager to use for installing dependencies (pip or poetry)
    required: false
    default: "pip"

  generate-pdf-report:
    description: Generate a PDF report using snyk-to-html
    required: false
    type: boolean
    default: false

  continue-on-error:
    description: Whether to continue workflow if Snyk scan fails
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      run: |
        echo "🔍 Validating inputs..."

        if [[ "${{ inputs.scan-mode }}" != "iac" && "${{ inputs.scan-mode }}" != "code" && "${{ inputs.scan-mode }}" != "sast" ]]; then
          echo "❌ Invalid scan-mode '${{ inputs.scan-mode }}'. Must be 'iac', 'code', or 'sast'."
          exit 1
        fi

        if [[ "${{ inputs.scan-mode }}" == "code" && -z "${{ inputs.code-file }}" ]]; then
          echo "❌ 'code-file' must be provided when scan-mode is 'code'."
          exit 1
        fi

        if [[ "${{ inputs.install-requirements }}" == "true" ]]; then
          if [[ "${{ inputs.python-package-manager }}" != "pip" && "${{ inputs.python-package-manager }}" != "poetry" ]]; then
            echo "❌ Invalid python-package-manager '${{ inputs.python-package-manager }}'. Must be 'pip' or 'poetry'."
            exit 1
          fi
        fi

        if [[ "${{ inputs.update-pr-with-scan-results }}" == "true" && -z "${{ inputs.json-output-file }}" ]]; then
          echo "❌ 'json-output-file' must be defined when update-pr-with-scan-results is true."
          exit 1
        fi

        echo "✅ All inputs look good."
      shell: bash

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Snyk CLI
      run: npm install -g snyk --quiet
      shell: bash

    - name: Configure Snyk Organization and Endpoint
      run: |
        snyk config set org=${{ inputs.snyk-org }}
        if [[ -n "${{ inputs.snyk-endpoint }}" ]]; then
          snyk config set endpoint=${{ inputs.snyk-endpoint }}
        fi
      shell: bash

    - name: Authenticate Snyk
      run: |
        if [[ -z "${{ inputs.snyk-token }}" ]]; then
          echo "Error: SNYK_TOKEN is not set"
          exit 1
        fi
        snyk auth "${{ inputs.snyk-token }}"
      shell: bash

    - name: Run Snyk IaC Scan
      if: ${{ inputs.scan-mode == 'iac' }}
      run: |
        snyk iac test --severity-threshold=${{ inputs.severity-threshold }} --report --json-file-output=${{ inputs.json-output-file }} || [ "${{ inputs.continue-on-error }}" == "true" ]
      shell: bash

    - name: Install Python requirements
      if: ${{ inputs.install-requirements == 'true' && inputs.scan-mode == 'code' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [[ "${{ inputs.python-package-manager }}" == "poetry" ]]; then
          pip install poetry
          poetry install --no-root
        else
          pip install -r ${{ inputs.code-file }}
        fi

    - name: Run Snyk Code Dependency Scan
      if: ${{ inputs.scan-mode == 'code' }}
      run: |
        CMD="snyk test --file=${{ inputs.code-file }} --severity-threshold=${{ inputs.severity-threshold }}"

        if [[ "${{ inputs.skip-unresolved }}" == "true" ]]; then
          CMD="$CMD --skip-unresolved"
        fi

        if [[ "${{ inputs.exclude-licenses }}" == "true" ]]; then
          CMD="$CMD --exclude-licenses"
        fi

        if [[ "${{ inputs.use-policy-file }}" == "true" ]]; then
          CMD="$CMD --policy-path=${{ inputs.policy-file-path }}"
        fi

        CMD="$CMD --json-file-output=${{ inputs.json-output-file }}"

        echo "Running: $CMD"
        eval "$CMD" || [ "${{ inputs.continue-on-error }}" == "true" ]
      shell: bash

    - name: Run Snyk SAST Scan
      if: ${{ inputs.scan-mode == 'sast' }}
      run: |
        CMD="snyk code test ${{ inputs.sast-path }} --severity-threshold=${{ inputs.severity-threshold }}"

        if [[ -n "${{ inputs.sast-include }}" ]]; then
          # Convert comma-separated list to multiple --include flags
          IFS=',' read -ra INCLUDES <<< "${{ inputs.sast-include }}"
          for include in "${INCLUDES[@]}"; do
            CMD="$CMD --include=$(echo $include | xargs)"
          done
        fi

        if [[ -n "${{ inputs.sast-exclude }}" ]]; then
          # Convert comma-separated list to multiple --exclude flags
          IFS=',' read -ra EXCLUDES <<< "${{ inputs.sast-exclude }}"
          for exclude in "${EXCLUDES[@]}"; do
            CMD="$CMD --exclude=$(echo $exclude | xargs)"
          done
        fi

        if [[ "${{ inputs.use-policy-file }}" == "true" ]]; then
          CMD="$CMD --policy-path=${{ inputs.policy-file-path }}"
        fi

        CMD="$CMD --json-file-output=${{ inputs.json-output-file }}"

        echo "Running: $CMD"
        eval "$CMD" || [ "${{ inputs.continue-on-error }}" == "true" ]
      shell: bash

    - name: Post results to PR
      if: ${{ always() && inputs.update-pr-with-scan-results == 'true' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const codeMarker = '<!-- snyk-scan-comment-code -->';
          const iacMarker = '<!-- snyk-scan-comment-iac -->';
          const sastMarker = '<!-- snyk-scan-comment-sast -->';

          const filePath = path.resolve('${{ inputs.json-output-file }}');
          if (!fs.existsSync(filePath)) {
            console.log('❌ Snyk output file not found:', filePath);
            return;
          }

          const results = JSON.parse(fs.readFileSync(filePath, 'utf8'));
          // Detect scan type based on the structure of results
          const isIacScan = Array.isArray(results) && results.some(r => r.hasOwnProperty('infrastructureAsCodeIssues'));
          const isSastScan = Array.isArray(results) && results.some(r => r.hasOwnProperty('runs'));
          
          let body = '';
          const number = context.payload.pull_request?.number ?? context.issue?.number;
          if (!number) {
            console.log('❌ Not running in a pull request context');
            return;
          }

          const comments = await github.rest.issues.listComments({
            issue_number: number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          console.log(`💬 Found ${comments.data.length} comments on this PR.`);

          const marker = isSastScan ? sastMarker : (isIacScan ? iacMarker : codeMarker);
          const existing = comments.data.find(c => c.body.includes(marker));

          if (isSastScan) {
            console.log('🛡️ Detected SAST scan format.');

            const allIssues = [];

            for (const result of results) {
              if (!result.runs || result.runs.length === 0) continue;

              for (const run of result.runs) {
                if (!run.results || run.results.length === 0) continue;

                for (const issue of run.results) {
                  const rule = run.tool?.driver?.rules?.find(r => r.id === issue.ruleId) || {};
                  const location = issue.locations?.[0]?.physicalLocation;
                  const filePath = location?.artifactLocation?.uri || 'Unknown file';
                  const startLine = location?.region?.startLine || 'N/A';

                  allIssues.push({
                    file: filePath,
                    line: startLine,
                    ruleId: issue.ruleId || 'N/A',
                    title: rule.shortDescription?.text || issue.message?.text || 'Unknown issue',
                    severity: issue.level || rule.defaultConfiguration?.level || 'unknown',
                    description: rule.fullDescription?.text || 'No description available',
                    helpUri: rule.helpUri || 'N/A'
                  });
                }
              }
            }

            if (allIssues.length === 0) {
              console.log('✅ No SAST issues found.');
              if (existing) {
                console.log('🧹 Deleting outdated SAST scan comment.');
                await github.rest.issues.deleteComment({
                  comment_id: existing.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
              }
              return;
            }

            // Create detailed markdown table for SAST issues
            let table = '| File | Line | Rule | Severity | Issue | Description | Help |\n|------|------|------|----------|-------|-------------|------|\n';

            for (const issue of allIssues) {
              const safeTitle = (issue.title || '').replace(/\|/g, '\\|').slice(0, 60);
              const safeDescription = (issue.description || '').replace(/\|/g, '\\|').slice(0, 80);
              const helpLink = issue.helpUri !== 'N/A' ? `[Info](${issue.helpUri})` : 'N/A';

              table += `| ${issue.file} | ${issue.line} | \`${issue.ruleId}\` | ${issue.severity} | ${safeTitle} | ${safeDescription} | ${helpLink} |\n`;
            }

            body = `${sastMarker}\n## 🛡️ Snyk SAST Scan Results\n\nFound ${allIssues.length} security issue${allIssues.length > 1 ? 's' : ''}:\n\n${table}`;

          } else if (isIacScan) {
            console.log('🔍 Detected IaC scan format.');

            // Collect all issues from all scan results
            const allIssues = [];

            for (const result of results) {
              if (result.ok === true && (!result.infrastructureAsCodeIssues || result.infrastructureAsCodeIssues.length === 0)) {
                continue; // Skip if no issues
              }

              const targetFile = result.targetFile || 'Unknown file';

              // Process each issue in the file
              if (result.infrastructureAsCodeIssues && result.infrastructureAsCodeIssues.length > 0) {
                for (const issue of result.infrastructureAsCodeIssues) {
                  allIssues.push({
                    file: targetFile,
                    id: issue.id || issue.publicId || 'N/A',
                    title: issue.title || (issue.iacDescription?.issue || 'Unknown issue'),
                    severity: issue.severity || 'unknown',
                    resourcePath: issue.msg || 'Unknown resource',
                    impact: issue.iacDescription?.impact || 'Not specified',
                    resolution: issue.iacDescription?.resolve || 'Not specified',
                    documentation: issue.documentation ||
                                  (issue.references && issue.references.length > 0 ? issue.references[0] : 'N/A')
                  });
                }
              }
            }

            if (allIssues.length === 0) {
              console.log('✅ No actionable issues in IaC scan.');
              if (existing) {
                console.log('🧹 Deleting outdated IaC scan comment.');
                await github.rest.issues.deleteComment({
                  comment_id: existing.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
              }
              return;
            }

            // Create detailed markdown table for IAC issues
            let table = '| File | Resource | Severity | Issue | Impact | Resolution | Link |\n|------|----------|----------|-------|--------|------------|------|\n';

            for (const issue of allIssues) {
              // Use backticks to format code-like elements and escape any pipe characters
              const safeTitle = issue.title.replace(/\|/g, '\\|');
              const safeImpact = issue.impact.replace(/\|/g, '\\|');
              const safeResolution = issue.resolution.replace(/\|/g, '\\|');

              table += `| ${issue.file} | \`${issue.resourcePath}\` | ${issue.severity} | ${safeTitle} | ${safeImpact} | ${safeResolution} | [Documentation](${issue.documentation}) |\n`;
            }

            body = `${iacMarker}\n## 📄 Snyk IaC Scan Results\n\nFound ${allIssues.length} infrastructure issue${allIssues.length > 1 ? 's' : ''}:\n\n${table}`;
          } else {
            console.log('🧪 Detected code scan format.');
            const vulns = results.vulnerabilities || [];
            if (vulns.length === 0) {
              if (existing) {
                await github.rest.issues.deleteComment({
                  comment_id: existing.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
              }
              return;
            }

            let table = '| Package | Version | Severity | Title | More Info |\n|---------|---------|----------|-------|------------|\n';
            const seen = new Set();

            for (const v of vulns) {
              const pkg = v.packageName || v.moduleName || 'unknown';
              const version = v.version || 'unknown';
              const severity = v.severity || 'unknown';
              const title = (v.title || 'unknown').replace(/\|/g, '-').slice(0, 80);

              let moreInfo = '';
              let refKey = ''; // part of the deduplication key

              const refs = Array.isArray(v.references) ? v.references.filter(r => typeof r === 'string') : [];
              const ref = refs.find(url =>
                url.includes('snyk.io/blog') ||
                url.includes('huntr.com') ||
                url.includes('snyk.io/vuln/') ||
                url.includes('gist.github.com')
              );

              if (ref) {
                const label = ref.includes('blog') ? 'Snyk Blog'
                            : ref.includes('huntr.com') ? 'PoC'
                            : ref.includes('vuln') ? 'Snyk'
                            : 'Details';
                moreInfo = `[${label}](${ref})`;
                refKey = ref;
              } else if (refs.length > 0) {
                moreInfo = `[Reference](${refs[0]})`;
                refKey = refs[0];
              } else if (v.identifiers?.CVE?.length > 0) {
                const cve = v.identifiers.CVE[0];
                moreInfo = `[CVE-${cve}](https://cve.mitre.org/cgi-bin/cvename.cgi?name=${cve})`;
                refKey = cve;
              }

              const signature = `${pkg}-${version}-${title}-${refKey}`;
              if (seen.has(signature)) continue;
              seen.add(signature);

              table += `| ${pkg} | ${version} | ${severity} | ${title} | ${moreInfo} |\n`;
            }
            body = `${codeMarker}\n## 🔍 Snyk Code Dependency Scan Results\n\n${table}`;
          }

          if (existing) {
            await github.rest.issues.updateComment({
              comment_id: existing.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
          }

    - name: Generate PDF report from scan
      if: ${{ inputs.generate-pdf-report == 'true' && (inputs.scan-mode == 'code' || inputs.scan-mode == 'sast') }}
      run: |
        npm install -g snyk-to-html
        sudo apt-get update && sudo apt-get install -y wkhtmltopdf
        snyk-to-html -i ${{ inputs.json-output-file }} -o snyk-report.html
        wkhtmltopdf snyk-report.html snyk-report.pdf
      shell: bash

    - name: Upload PDF report as artifact
      if: ${{ inputs.generate-pdf-report == 'true' && (inputs.scan-mode == 'code' || inputs.scan-mode == 'sast') }}
      uses: actions/upload-artifact@v4
      with:
        name: snyk-pdf-report-${{ inputs.scan-mode }}
        path: snyk-report.pdf
