name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Read version and major tag
        id: version_info
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            MAJOR=$(echo "$TAG" | grep -oE '^v[0-9]+')
            echo "VERSION=$TAG" >> $GITHUB_ENV
            echo "MAJOR_VERSION=$MAJOR" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body_path: README.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Update major version tag (e.g., v1, v2, v3)
        env:
            GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
            echo "Updating major version tag: $MAJOR_VERSION"
  
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
  
            git tag -f "$MAJOR_VERSION"
            git push origin -f "$MAJOR_VERSION"